source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StringIsNotEmpty_Example', :exclusive => true do
  pod "StringIsNotEmpty", :path => "../"
end

target 'StringIsNotEmpty_Tests', :exclusive => true do
  pod "StringIsNotEmpty", :path => "../"

  
end
